workspace(name = "io_bazel_rules_dotnet")

load("//dotnet:defs.bzl", "dotnet_register_toolchains", "dotnet_repositories", 
        "dotnet_nuget_new", "net_gac4", "vs2017_ref_net", "nuget_package")

dotnet_repositories()
dotnet_register_toolchains("host")

nuget_package(
   name = "npgsql",
   package = "npgsql",
   version = "4.0.3",
   sha256 = "4e1f91eb9f0c3dfb8e029edbc325175cd202455df3641bc16155ef422b6bfd6f",
   core_lib = "lib/netstandard2.0/Npgsql.dll",
   net_lib = "lib/net451/Npgsql.dll",
   mono_lib = "lib/net45/Npgsql.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard2.0/Npgsql.dll",
       "lib/netstandard2.0/Npgsql.pdb",
       "lib/netstandard2.0/Npgsql.xml",
   ],
   net_files = [
       "lib/net451/Npgsql.dll",
       "lib/net451/Npgsql.pdb",
       "lib/net451/Npgsql.xml",
   ],
   mono_files = [
       "lib/net45/Npgsql.dll",
       "lib/net45/Npgsql.pdb",
       "lib/net45/Npgsql.xml",
   ],
)

net_gac4(
  name = "System.ComponentModel.DataAnnotations",
  version = "4.0.0.0",
  token = "31bf3856ad364e35"
)

# The rule is left as an example. It is commented out, because our CI server doesn't have VS2017 installed
# vs2017_ref_net(name = "vs2017_ref")

load("@io_bazel_rules_dotnet//tests:bazel_tests.bzl", "test_environment")

test_environment()

### Generated by the tool
nuget_package(
   name = "system.collections",
   package = "system.collections",
   version = "4.0.11",
   sha256 = "b29dd3b088542772a80853f14ef38c91b48ba2e04d75af253ed0febbaed572a6",
   core_lib = "ref/netstandard1.3/System.Collections.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.console",
   package = "system.console",
   version = "4.0.0",
   sha256 = "4307b84135be5435fb281b91aea18c795133269bd997fce6927d6bc0c655803b",
   core_lib = "ref/netstandard1.3/System.Console.dll",
   net_lib = "ref/net46/System.Console.dll",
   mono_lib = "ref/net46/System.Console.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net46/System.Console.dll",
   ],
   mono_files = [
       "lib/net46/System.Console.dll",
   ],
)
nuget_package(
   name = "system.diagnostics.debug",
   package = "system.diagnostics.debug",
   version = "4.0.11",
   sha256 = "c3b2ee001ac3950748d518be80cd2334625ab6068fe788a4ae0a8b73d9fe8c48",
   core_lib = "ref/netstandard1.3/System.Diagnostics.Debug.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.globalization",
   package = "system.globalization",
   version = "4.0.11",
   sha256 = "de730e6633e5a5b548e08493eacd11d96d0d2af52469cd572e411b03a365fe12",
   core_lib = "ref/netstandard1.3/System.Globalization.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.io",
   package = "system.io",
   version = "4.1.0",
   sha256 = "08ff299728070117ec28e073568821e24740cc14673587f9dfa7d7c80d2a3a37",
   core_lib = "ref/netstandard1.5/System.IO.dll",
   net_lib = "ref/net462/System.IO.dll",
   mono_lib = "ref/net462/System.IO.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net462/System.IO.dll",
   ],
   mono_files = [
       "lib/net462/System.IO.dll",
   ],
)
nuget_package(
   name = "system.linq.expressions",
   package = "system.linq.expressions",
   version = "4.1.0",
   sha256 = "13dbcc5ef76d1297b51fad2e712678ae4ffdc7ee462ac38a8f1fb6e2050d1fc8",
   core_lib = "ref/netstandard1.6/System.Linq.Expressions.dll",
   net_lib = "ref/net463/System.Linq.Expressions.dll",
   mono_lib = "ref/net463/System.Linq.Expressions.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/System.Linq.Expressions.dll",
   ],
   net_files = [
       "lib/net463/System.Linq.Expressions.dll",
   ],
   mono_files = [
       "lib/net463/System.Linq.Expressions.dll",
   ],
)
nuget_package(
   name = "system.reflection",
   package = "system.reflection",
   version = "4.1.0",
   sha256 = "92876be0a2f4e933a5396dc42b1f6cf9e24c8422513fb8969665b87629ad6b00",
   core_lib = "ref/netstandard1.5/System.Reflection.dll",
   net_lib = "ref/net462/System.Reflection.dll",
   mono_lib = "ref/net462/System.Reflection.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net462/System.Reflection.dll",
   ],
   mono_files = [
       "lib/net462/System.Reflection.dll",
   ],
)
nuget_package(
   name = "system.reflection.extensions",
   package = "system.reflection.extensions",
   version = "4.0.1",
   sha256 = "c7ef29b83227a6fd8e97762e7bdb8ac814ce9e29f105ff73f899796ac58b2fd8",
   core_lib = "ref/netstandard1.0/System.Reflection.Extensions.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.reflection.typeextensions",
   package = "system.reflection.typeextensions",
   version = "4.1.0",
   sha256 = "488cb2fc25325e3d6375d853762bba08e1c87c1fa5f11f332cfbfdddd47ec28f",
   core_lib = "ref/netstandard1.5/System.Reflection.TypeExtensions.dll",
   net_lib = "ref/net462/System.Reflection.TypeExtensions.dll",
   mono_lib = "ref/net462/System.Reflection.TypeExtensions.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.5/System.Reflection.TypeExtensions.dll",
   ],
   net_files = [
       "lib/net462/System.Reflection.TypeExtensions.dll",
   ],
   mono_files = [
       "lib/net462/System.Reflection.TypeExtensions.dll",
   ],
)
nuget_package(
   name = "system.resources.resourcemanager",
   package = "system.resources.resourcemanager",
   version = "4.0.1",
   sha256 = "9e25f4aa24be51f0d3e62d620ce46a814afcd1182aec5577c58795bcb3f954c2",
   core_lib = "ref/netstandard1.0/System.Resources.ResourceManager.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.runtime",
   package = "system.runtime",
   version = "4.1.0",
   sha256 = "f9563014a56311b04bd8ccf6461909f8ce912c53aa4bc1cbb5f2e1a1811cc716",
   core_lib = "ref/netstandard1.5/System.Runtime.dll",
   net_lib = "ref/net462/System.Runtime.dll",
   mono_lib = "ref/net462/System.Runtime.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net462/System.Runtime.dll",
   ],
   mono_files = [
       "lib/net462/System.Runtime.dll",
   ],
)
nuget_package(
   name = "system.runtime.extensions",
   package = "system.runtime.extensions",
   version = "4.1.0",
   sha256 = "cc13705200fc4df730dc971b3188a10e0492c06c9296f3dc9c2061e1e041ba2e",
   core_lib = "ref/netstandard1.5/System.Runtime.Extensions.dll",
   net_lib = "ref/net462/System.Runtime.Extensions.dll",
   mono_lib = "ref/net462/System.Runtime.Extensions.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net462/System.Runtime.Extensions.dll",
   ],
   mono_files = [
       "lib/net462/System.Runtime.Extensions.dll",
   ],
)
nuget_package(
   name = "commandlineparser",
   package = "commandlineparser",
   version = "2.3.0",
   sha256 = "09e60ff23e6953b4fe7d267ef552d8ece76404acf44842012f84430e8b877b13",
   core_lib = "lib/netstandard1.5/CommandLine.dll",
   net_lib = "lib/net45/CommandLine.dll",
   mono_lib = "lib/net45/CommandLine.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.5/CommandLine.dll",
       "lib/netstandard1.5/CommandLine.xml",
   ],
   net_files = [
       "lib/net45/CommandLine.dll",
       "lib/net45/CommandLine.XML",
   ],
   mono_files = [
       "lib/net45/CommandLine.dll",
       "lib/net45/CommandLine.XML",
   ],
)
nuget_package(
   name = "newtonsoft.json",
   package = "newtonsoft.json",
   version = "11.0.2",
   sha256 = "679e438d5eb7d7e5599aa71b65fd23ee50dabf57579607873b87d34aec11ca1e",
   core_lib = "lib/netstandard2.0/Newtonsoft.Json.dll",
   net_lib = "lib/net45/Newtonsoft.Json.dll",
   mono_lib = "lib/net45/Newtonsoft.Json.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard2.0/Newtonsoft.Json.dll",
       "lib/netstandard2.0/Newtonsoft.Json.xml",
   ],
   net_files = [
       "lib/net45/Newtonsoft.Json.dll",
       "lib/net45/Newtonsoft.Json.xml",
   ],
   mono_files = [
       "lib/net45/Newtonsoft.Json.dll",
       "lib/net45/Newtonsoft.Json.xml",
   ],
)
nuget_package(
   name = "nuget.frameworks",
   package = "nuget.frameworks",
   version = "4.8.0",
   sha256 = "0228601ad2becf5ec3825882f556fdd821e2f470e504a659acdeabc908ce9060",
   core_lib = "lib/netstandard1.6/NuGet.Frameworks.dll",
   net_lib = "lib/net46/NuGet.Frameworks.dll",
   mono_lib = "lib/net46/NuGet.Frameworks.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Frameworks.dll",
       "lib/netstandard1.6/NuGet.Frameworks.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Frameworks.dll",
       "lib/net46/NuGet.Frameworks.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Frameworks.dll",
       "lib/net46/NuGet.Frameworks.xml",
   ],
)
nuget_package(
   name = "nuget.common",
   package = "nuget.common",
   version = "4.8.0",
   sha256 = "1e1fe6c30798661ee1ee1342c444a4ef0c3113a6ef5e3c4105de70fbcb01562e",
   core_lib = "lib/netstandard1.6/NuGet.Common.dll",
   net_lib = "lib/net46/NuGet.Common.dll",
   mono_lib = "lib/net46/NuGet.Common.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Common.dll",
       "lib/netstandard1.6/NuGet.Common.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Common.dll",
       "lib/net46/NuGet.Common.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Common.dll",
       "lib/net46/NuGet.Common.xml",
   ],
)
nuget_package(
   name = "nuget.configuration",
   package = "nuget.configuration",
   version = "4.8.0",
   sha256 = "c6dcd79a03353d3e9296f52f7b0206430aca7ec3332a61424e28dc6d6a03ffc5",
   core_lib = "lib/netstandard1.6/NuGet.Configuration.dll",
   net_lib = "lib/net46/NuGet.Configuration.dll",
   mono_lib = "lib/net46/NuGet.Configuration.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Configuration.dll",
       "lib/netstandard1.6/NuGet.Configuration.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Configuration.dll",
       "lib/net46/NuGet.Configuration.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Configuration.dll",
       "lib/net46/NuGet.Configuration.xml",
   ],
)
nuget_package(
   name = "microsoft.web.xdt",
   package = "microsoft.web.xdt",
   version = "2.1.2",
   sha256 = "ba0649bf72baa8e574feaaa366774d8eadfa6f2c65ae11326a45661b5815c88b",
   core_lib = "",
   net_lib = "lib/net40/Microsoft.Web.XmlTransform.dll",
   mono_lib = "lib/net40/Microsoft.Web.XmlTransform.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net40/Microsoft.Web.XmlTransform.dll",
   ],
   mono_files = [
       "lib/net40/Microsoft.Web.XmlTransform.dll",
   ],
)
nuget_package(
   name = "nuget.versioning",
   package = "nuget.versioning",
   version = "4.8.0",
   sha256 = "1595aee52364a56853c8d339eb18354cd1342628a0d1d15bcd296e38509dd534",
   core_lib = "lib/netstandard1.6/NuGet.Versioning.dll",
   net_lib = "lib/net46/NuGet.Versioning.dll",
   mono_lib = "lib/net46/NuGet.Versioning.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Versioning.dll",
       "lib/netstandard1.6/NuGet.Versioning.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Versioning.dll",
       "lib/net46/NuGet.Versioning.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Versioning.dll",
       "lib/net46/NuGet.Versioning.xml",
   ],
)
nuget_package(
   name = "nuget.librarymodel",
   package = "nuget.librarymodel",
   version = "4.8.0",
   sha256 = "caf98979fdc9202d610d9fe74204b92b0e4a25e458fab8a6208297b5a78d005d",
   core_lib = "lib/netstandard1.6/NuGet.LibraryModel.dll",
   net_lib = "lib/net46/NuGet.LibraryModel.dll",
   mono_lib = "lib/net46/NuGet.LibraryModel.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.LibraryModel.dll",
       "lib/netstandard1.6/NuGet.LibraryModel.xml",
   ],
   net_files = [
       "lib/net46/NuGet.LibraryModel.dll",
       "lib/net46/NuGet.LibraryModel.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.LibraryModel.dll",
       "lib/net46/NuGet.LibraryModel.xml",
   ],
)
nuget_package(
   name = "nuget.packaging.core",
   package = "nuget.packaging.core",
   version = "4.8.0",
   sha256 = "3002b9a69887e8452bc21693117c60a0d39c4d0fc55d3e584d9770237b9ba57a",
   core_lib = "lib/netstandard1.6/NuGet.Packaging.Core.dll",
   net_lib = "lib/net46/NuGet.Packaging.Core.dll",
   mono_lib = "lib/net46/NuGet.Packaging.Core.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Packaging.Core.dll",
       "lib/netstandard1.6/NuGet.Packaging.Core.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Packaging.Core.dll",
       "lib/net46/NuGet.Packaging.Core.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Packaging.Core.dll",
       "lib/net46/NuGet.Packaging.Core.xml",
   ],
)
nuget_package(
   name = "nuget.packaging",
   package = "nuget.packaging",
   version = "4.8.0",
   sha256 = "43f8f20c4312de46d44d62411abdb647b739fff451cd0d06534851a55a97228f",
   core_lib = "lib/netstandard1.6/NuGet.Packaging.dll",
   net_lib = "lib/net46/NuGet.Packaging.dll",
   mono_lib = "lib/net46/NuGet.Packaging.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Packaging.dll",
       "lib/netstandard1.6/NuGet.Packaging.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Packaging.dll",
       "lib/net46/NuGet.Packaging.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Packaging.dll",
       "lib/net46/NuGet.Packaging.xml",
   ],
)
nuget_package(
   name = "nuget.protocol",
   package = "nuget.protocol",
   version = "4.8.0",
   sha256 = "c48ce771fc8c9b7d3ee736ef79890a43683936b224a89a0fcd9772d94c64f24c",
   core_lib = "lib/netstandard1.6/NuGet.Protocol.dll",
   net_lib = "lib/net46/NuGet.Protocol.dll",
   mono_lib = "lib/net46/NuGet.Protocol.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Protocol.dll",
       "lib/netstandard1.6/NuGet.Protocol.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Protocol.dll",
       "lib/net46/NuGet.Protocol.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Protocol.dll",
       "lib/net46/NuGet.Protocol.xml",
   ],
)
nuget_package(
   name = "nuget.credentials",
   package = "nuget.credentials",
   version = "4.8.0",
   sha256 = "06f11610731918ecde42acb683bb0656b74897106e0edcb109cd9b40535f65fd",
   core_lib = "lib/netstandard1.6/NuGet.Credentials.dll",
   net_lib = "lib/net46/NuGet.Credentials.dll",
   mono_lib = "lib/net46/NuGet.Credentials.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Credentials.dll",
   ],
   net_files = [
       "lib/net46/NuGet.Credentials.dll",
   ],
   mono_files = [
       "lib/net46/NuGet.Credentials.dll",
   ],
)
nuget_package(
   name = "nuget.dependencyresolver.core",
   package = "nuget.dependencyresolver.core",
   version = "4.8.0",
   sha256 = "d31e1377de8db1d82109b9813587688073f17b4249baeb99a6743eb266753682",
   core_lib = "lib/netstandard1.6/NuGet.DependencyResolver.Core.dll",
   net_lib = "lib/net46/NuGet.DependencyResolver.Core.dll",
   mono_lib = "lib/net46/NuGet.DependencyResolver.Core.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.DependencyResolver.Core.dll",
       "lib/netstandard1.6/NuGet.DependencyResolver.Core.xml",
   ],
   net_files = [
       "lib/net46/NuGet.DependencyResolver.Core.dll",
       "lib/net46/NuGet.DependencyResolver.Core.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.DependencyResolver.Core.dll",
       "lib/net46/NuGet.DependencyResolver.Core.xml",
   ],
)
nuget_package(
   name = "nuget.projectmodel",
   package = "nuget.projectmodel",
   version = "4.8.0",
   sha256 = "27dd4cb819d95c06e74b0548edf05594e6be96f51fc72d460b9e0bdc12fe4479",
   core_lib = "lib/netstandard1.6/NuGet.ProjectModel.dll",
   net_lib = "lib/net46/NuGet.ProjectModel.dll",
   mono_lib = "lib/net46/NuGet.ProjectModel.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.ProjectModel.dll",
       "lib/netstandard1.6/NuGet.ProjectModel.xml",
   ],
   net_files = [
       "lib/net46/NuGet.ProjectModel.dll",
       "lib/net46/NuGet.ProjectModel.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.ProjectModel.dll",
       "lib/net46/NuGet.ProjectModel.xml",
   ],
)
nuget_package(
   name = "nuget.commands",
   package = "nuget.commands",
   version = "4.8.0",
   sha256 = "56f9396b760a77af914fd9d419bf7c878305301c43ab0268f8b51b86c990394f",
   core_lib = "lib/netstandard1.6/NuGet.Commands.dll",
   net_lib = "lib/net46/NuGet.Commands.dll",
   mono_lib = "lib/net46/NuGet.Commands.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Commands.dll",
       "lib/netstandard1.6/NuGet.Commands.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Commands.dll",
       "lib/net46/NuGet.Commands.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Commands.dll",
       "lib/net46/NuGet.Commands.xml",
   ],
)
nuget_package(
   name = "nuget.resolver",
   package = "nuget.resolver",
   version = "4.8.0",
   sha256 = "d3c69eba7912022e0d5dac08f0a3085b9885fe53ac914ffac8146fe8b4c15468",
   core_lib = "lib/netstandard1.6/NuGet.Resolver.dll",
   net_lib = "lib/net46/NuGet.Resolver.dll",
   mono_lib = "lib/net46/NuGet.Resolver.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/NuGet.Resolver.dll",
       "lib/netstandard1.6/NuGet.Resolver.xml",
   ],
   net_files = [
       "lib/net46/NuGet.Resolver.dll",
       "lib/net46/NuGet.Resolver.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.Resolver.dll",
       "lib/net46/NuGet.Resolver.xml",
   ],
)
nuget_package(
   name = "nuget.packagemanagement",
   package = "nuget.packagemanagement",
   version = "4.8.0",
   sha256 = "386a5f74a2564c6e10f210a8fdb5a40d0f9deb53c3368428da45d96f01889003",
   core_lib = "lib/net46/NuGet.PackageManagement.dll",
   net_lib = "lib/net46/NuGet.PackageManagement.dll",
   mono_lib = "lib/net46/NuGet.PackageManagement.dll",
   deps = [
   ],
   core_files = [
   ],
   net_files = [
       "lib/net46/NuGet.PackageManagement.dll",
       "lib/net46/NuGet.PackageManagement.xml",
   ],
   mono_files = [
       "lib/net46/NuGet.PackageManagement.dll",
       "lib/net46/NuGet.PackageManagement.xml",
   ],
)
nuget_package(
   name = "system.xml.xdocument",
   package = "system.xml.xdocument",
   version = "4.3.0",
   sha256 = "4e48005cef204b82a4102ec9827f13ee9799cff5a8f7c925cf46ad6a293c4592",
   core_lib = "ref/netstandard1.3/System.Xml.XDocument.dll",
   net_lib = "",
   mono_lib = "",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.3/System.Xml.XDocument.dll",
   ],
   net_files = [
   ],
   mono_files = [
   ],
)
nuget_package(
   name = "system.linq",
   package = "system.linq",
   version = "4.3.0",
   sha256 = "693327b2ecee67b8a04ea58c98ae449020305339f71cef78a45bd845e7e22990",
   core_lib = "ref/netstandard1.6/System.Linq.dll",
   net_lib = "ref/net463/System.Linq.dll",
   mono_lib = "ref/net463/System.Linq.dll",
   deps = [
   ],
   core_files = [
       "lib/netstandard1.6/System.Linq.dll",
   ],
   net_files = [
       "lib/net463/System.Linq.dll",
   ],
   mono_files = [
       "lib/net463/System.Linq.dll",
   ],
)
### End of generated by the tool
