'''
load("//dotnet:csharp.bzl", "csharp_binary")

csharp_binary(
    name = "hello",
    srcs = [
        "Program.cs",
        "Properties/AssemblyInfo.cs",
    ],
    deps = [
        "//examples/example_lib:MyClass",
    ],
)
'''