filegroup(
    name = "all_rules",
    srcs = glob([
        "**/*.bzl",
    ]),
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "toolchain",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "toolchain_core",
    visibility = ["//visibility:public"],
)

toolchain_type(
    name = "toolchain_net",
    visibility = ["//visibility:public"],
)
