package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = glob([
        "*.c",
    ]),
    hdrs = glob([
        "*.h",
    ]),
)

exports_files(["manifest.h"])
