# This file declares a config_setting for each platform supported by the
# Dotnet. These rules follow a os_arch naming convention, for example,
# //dotnet/platform:linux_amd64
#
# These can be used in select expressions to choose platform-specifc
# sources and dependencies.

package(default_visibility = ["//visibility:public"])

load(":list.bzl", "declare_config_settings")

declare_config_settings()

